### ISSUE TITLE
stacktrace with --format human when there's no end time

### ISSUE THREAD

**Issue by rzimmerman** [planetlabs/datalake#33]
Using:
`datalake list ops-down-list --where xxx --start 2016-07-01T00:00Z --end 2016-07-07T00:00Z --format human`

When one of the results has a null end time gave me this traceback:

```
Traceback (most recent call last):
  File "/Users/rob/venvs/datalake-staging/bin/datalake", line 11, in <module>
    sys.exit(cli())
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/datalake/scripts/cli.py", line 247, in list
    _list(**kwargs)
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/datalake/scripts/cli.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/datalake/scripts/cli.py", line 255, in _list
    _print_list_results(results, format)
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/datalake/scripts/cli.py", line 260, in _print_list_results
    s = _list_result_formatters[format](r)
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/datalake/scripts/cli.py", line 215, in _human_format
    s += _human_format(v)
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/datalake/scripts/cli.py", line 218, in _human_format
    v = _ms_to_iso(v)
  File "/Users/rob/venvs/datalake-staging/lib/python2.7/site-packages/datalake/scripts/cli.py", line 208, in _ms_to_iso
    return datetime.fromtimestamp(ms/1000.0, utc).isoformat()
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by rzimmerman** [comment]
Should not --json-pretty and other formatting options seem to handle it fine.

**Comment by mpsiegers** [comment]
Just ran into this today also.
