### ISSUE TITLE
Pushing datalake files reads entire file into memory

### ISSUE THREAD

**Issue by jof** [planetlabs/datalake#44]
I hit an unpleasant "bug" in Datalake today. We have a system which operates with most memory allocated to other processes during normal usage.
This system also generates some relatively large objects to push into datalake (videos, in this case).
I was notified about disk usage climbing and climbing, and upon further investigation, I found that `datalake uploader` had stopped running with a stacktrace like:
```
Traceback (most recent call last):
  File "/usr/local/bin/datalake", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/datalake/scripts/cli.py", line 193, in uploader
    _uploader(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/datalake/scripts/cli.py", line 30, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/datalake/scripts/cli.py", line 202, in _uploader
    u.listen(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/datalake/queue.py", line 134, in listen
    self._listen(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/datalake/queue.py", line 147, in _listen
    self._push(path)
  File "/usr/local/lib/python2.7/dist-packages/datalake/queue.py", line 127, in _push
    url = self._archive.push(f)
  File "/usr/local/lib/python2.7/dist-packages/datalake/archive.py", line 155, in push
    self._upload_file(f)
  File "/usr/local/lib/python2.7/dist-packages/datalake/archive.py", line 161, in _upload_file
    key.set_contents_from_string(f.read())
  File "/usr/lib/python2.7/tarfile.py", line 816, in read
    buf += self.fileobj.read()
  File "/usr/lib/python2.7/tarfile.py", line 736, in read
    return self.readnormal(size)
  File "/usr/lib/python2.7/tarfile.py", line 745, in readnormal
    return self.fileobj.read(size)
MemoryError
```

Around here: https://github.com/planetlabs/datalake/blob/d8952c71948a8d13ae5ce30322c37ae05e7bfb36/datalake/archive.py#L176 it seems that datalake is reading in the entire "content" of the file and uploading it as a binary string with the S3 API.
Is there a compelling reason to pull the entire object into memory?

If not, I would propose switching `boto.S3.Key.set_contents_from_string(f.read())` to be `boto.S3.Key.set_contents_from_file(f)` instead, as `TarFile.extractfile()` appears to cleanly support the file IO interface without reading everything in.

**Comment by bcavagnolo** [comment]
fixed in 0.26.
